<a href="#/app/users/create" class="user createBtn waves-effect waves-light btn green"><i class="material-icons left">add</i>Crear</a>
<a href="#/app/users/delete/{{seleccionado}}" class="user deleteBtn waves-effect waves-light btn red"><i class="material-icons left">delete</i>Eliminar</a>
<a href="#/app/users/modify/{{seleccionado}}" class="user modifyBtn waves-effect waves-light btn yellow"><i class="material-icons left">edit</i>Modificar</a>


<div class="row">
	<div ordenable id="admin" class="col s12">
		<div class="card material-table">
			<div class="table-header">
				<span class="table-title">Usuarios</span>
                <div class="actions">
                    <button ng-click="reverse()" class="waves-effect btn-flat nopadding"><i class="material-icons">import_export</i></button>
                </div>
			</div>
			<table id="datatable">
				<thead>
				<tr>
                    <th ng-click="order('id')">ID</th>
					<th ng-click="order('username')">Usuario</th>
					<th ng-click="order('name')">Nombre</th>
					<th ng-click="order('surname')">Apellidos</th>
					<th ng-click="order('phone')">Teléfono</th>
					<th ng-click="order('email')">Email</th>
                    <th ng-click="order('enabled')">Enabled</th>
				</tr>
				</thead>
				<tbody  ng-show="users.length > 0">
					<tr seleccionable-tr id="{{user.id}}" ng-repeat="user in users | orderBy:predicate:rever">
                        <td>{{user.id}}</td>
						<td >{{user.username}}</td>
						<td >{{user.name}}</td>
						<td >{{user.surname}}</td>
						<td >{{user.phone}}</td>
						<td >{{user.email}}</td>
						<td >{{user.enabled}}</td>
					</tr>
				</tbody>
				<tbody ng-show="!users.length > 0">
					<tr ng-show="users == undefined">
						<div ng-show="users == undefined" class="progress">
							<div class="indeterminate"></div>
						</div>
					</tr>
					<tr ng-show="users != undefined">
						<td colspan="6" class="center-align">No hay usuarios que visualizar.</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

