<div class="col s12 m5 offset-m1" ng-repeat="(index, court) in courts">
    <h3 ng-style="court.statusColor">Court {{court.id}}</h3>
    <div class="row center">
        <div ng-class="court.color" class="col s6 {{court.color}} lighten-2 paddle-court-cell valign-wrapper"
             ng-repeat="(indexP, player) in court.players">
            <span ng-show="!player.id" class="valign center-block">{{indexP + 1}}</span>
            <span ng-show="player.id" class="valign center-block">{{player.name}}</span>
        </div>
    </div>
</div>
<div class="col s12" ng-show="courts == null">
    <div ng-show="courts == null" class="progress">
        <div class="indeterminate"></div>
    </div>
</div>