<section ng-show="operacion != 'modify' && operacion != 'create'">
    <p class="center-align">¿Está seguro de que quiere eliminar la reserva '{{reservaId}}'?<br/>
        No habrá modo de recuperar los datos después de efectuarse la operación.</p><br/><br/>
</section>
<section ng-show="operacion == 'modify' || operacion == 'create'">
    <div class="row">
        <div class="col s12 m4" ng-controller="PlayerController">
            <lista-players></lista-players>
        </div>

        <div class="col s12 offset-m1 m7" ng-controller="CourtController">
            <lista-pistas></lista-pistas>
        </div>
    </div>
    <div style="height:200px">

    </div>
    <footer style="position:fixed; left:0px; bottom:0px; width:100%; height:200px; z-index:999999;" class="grey lighten-2">
        <br/><br/>
        <div class="container">
            <toolbar-reserva operacion-indicada="operacion" reserva-id="reservaId"></toolbar-reserva>
        </div>
    </footer>
</section>