<div class="row">
    <div class="col s12" id="feedback"></div>
    <form common-view modify-function="injectCallback(callback)" class="col s12">
    <section ng-show="(operacion == 'create' && !validated)">
        <div ng-show="operacion === 'create'" class="input-field col s6">
            <input placeholder="Username" ng-model="user.username" id="username" type="text" class="validate" required>
            <label class="active" data-error="Inválido" data-success="Correcto" for="username">Username</label>
        </div>
        <div class="input-field col s6">
            <input placeholder="E-mail" ng-model="user.email" id="email" type="email" class="validate" required>
            <label class="active" data-error="Inválido" data-success="Correcto" for="email">E-mail</label>
        </div>
    </section>
    <section ng-show="(operacion == 'create' && validated) || operacion == 'modify'">
          <div ng-show="operacion === 'create'" class="input-field col s6">
              <input placeholder="Username" ng-model="user.username" id="username" ng-disabled="validated" type="text" class="validate" required>
              <label class="active" data-error="Inválido" data-success="Correcto" for="username">Username</label>
          </div>
          <div ng-show="operacion === 'modify'" class="input-field col s6">
               <input placeholder="Username" ng-model="user.username" type="text" disabled id="usernam" type="text">
               <label class="active" data-error="Inválido" data-success="Correcto" for="username">Username</label>
          </div>

          <div class="input-field col s6">
               <input placeholder="Password" ng-model="user.password" id="password" type="password" class="validate" required>
               <label class="active" data-error="Inválido" data-success="Correcto" for="password">Password</label>
          </div>

          <div class="input-field col s6">
               <input placeholder="Nombre" ng-model="user.name" id="name" type="text" class="validate" required="">
               <label class="active" data-error="Inválido" data-success="Correcto" for="name">Nombre</label>
          </div>

          <div class="input-field col s6">
               <input placeholder="Apellidos" ng-model="user.surname" id="surname" type="text" class="validate" required>
               <label class="active" data-error="Inválido" data-success="Correcto" for="surname">Apellidos</label>
          </div>

          <div class="input-field col s6">
               <input placeholder="Teléfono" ng-model="user.phone" id="phone" type="tel" class="validate" required pattern="\d{3}(?:[\-]?)\d{3}(?:[\-]?)\d{3}">
               <label class="active" data-error="Inválido" data-success="Correcto" for="phone">Teléfono</label>
          </div>

          <div class="input-field col s6">
               <input placeholder="E-mail" ng-model="user.email" id="email" type="email" ng-disabled="validated" class="validate" required>
               <label class="active" data-error="Inválido" data-success="Correcto" for="email">E-mail</label>
          </div>

          <div ng-show="operacion == 'modify' && AppAuth.roles.indexOf('ROLE_ADMIN') > -1" class="input-field col s12">
            <p>
              <input type="checkbox" ng-model="user.enabled" id="enabled" />
              <label for="enabled">Enabled</label>
            </p>
            <p>
              <input type="checkbox" ng-model="user.admin" id="admin" />
              <label for="admin">Administrador</label>
            </p>
          </div>
    </section>
    <section ng-show="operacion != 'modify' && operacion != 'create'">
        <p class="center-align">¿Está seguro de que quiere eliminar el usuario '{{user.username}}'?<br/>
        No habrá modo de recuperar los datos después de efectuarse la operación.</p><br/><br/>
    </section>
  
  <div class="center-align">
      <button onclick="window.history.back();" class="waves-effect waves-light btn">Cancelar</button>
      <button ng-show="operacion == 'create' && validated" ng-click="create()" formnovalidate class="waves-effect waves-light btn" ng-disabled="isInvalid()">Aceptar</button>
      <button ng-show="operacion == 'create' && !validated" ng-click="validate()" formnovalidate class="waves-effect waves-light btn">Aceptar</button>
      <button ng-show="operacion == 'modify'" ng-click="update()" formnovalidate class="waves-effect waves-light btn">Aceptar</button>
      <button ng-show="operacion != 'modify' && operacion != 'create'" ng-click="delete()" formnovalidate class="waves-effect waves-light btn">Aceptar</button>
  </div>
  </form>

    <section ng-show="AppAuth.roles.indexOf('ROLE_ADMIN') > -1" ng-controller="ReservaController">
        <link rel="stylesheet" href="../css/datatable.css">
        <crude-misreservas usuario-id="userId"></crude-misreservas>
    </section>
</div>